### ISSUE TITLE
Add README.txt and LICENSE.txt

### ISSUE THREAD

**Issue by jwhitlock** [mdn/script-processor-node#1]
The README can refer to where this code is used on MDN.

The LICENSE file should be compatible with the statement [about copyright and licenses](https://developer.mozilla.org/en-US/docs/MDN/About#Copyrights_and_licenses) on MDN. If we intend to release to the public domain, the [unlicense](http://choosealicense.com/licenses/unlicense/) is a good choice.

Markdown (README.md) is also supported.

**Comment by chrisdavidmills** [comment]
I've added the files - do you think these look like good examples? the unlicense looks good to me for our public domain code file wish. Is there any way we could make it so that every repo created under mdn/ has this license added automatically?

**Comment by jwhitlock** [comment]
Yes, those files are perfect.

When creating the repo, you can select "Initialize the repository with a README" and pick "The Unlicense" as the license.

![repo_create](https://cloud.githubusercontent.com/assets/286017/15159795/0115c5a0-16bc-11e6-8c95-cf6df689063e.png)

**Comment by chrisdavidmills** [comment]
Cool, thanks!

BTW, I've updated the license to CC-0; I checked with the writer's team, and we apparently agreed a couple of years ago to use CC-0 for this purpose, for maximum portability.
